/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoostRouteImport } from './routes/boost'
import { Route as CreateRouteImport } from './routes/create'
import { Route as EcoRouteImport } from './routes/eco'
import { Route as MasterAdminRouteImport } from './routes/master-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoostRoute = BoostRouteImport.update({
  id: '/boost',
  path: '/boost',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EcoRoute = EcoRouteImport.update({
  id: '/eco',
  path: '/eco',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterAdminRoute = MasterAdminRouteImport.update({
  id: '/master-admin',
  path: '/master-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boost': typeof BoostRoute
  '/create': typeof CreateRoute
  '/eco': typeof EcoRoute
  '/master-admin': typeof MasterAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boost': typeof BoostRoute
  '/create': typeof CreateRoute
  '/eco': typeof EcoRoute
  '/master-admin': typeof MasterAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boost': typeof BoostRoute
  '/create': typeof CreateRoute
  '/eco': typeof EcoRoute
  '/master-admin': typeof MasterAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boost' | '/create' | '/eco' | '/master-admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boost' | '/create' | '/eco' | '/master-admin'
  id: '__root__' | '/' | '/boost' | '/create' | '/eco' | '/master-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoostRoute: typeof BoostRoute
  CreateRoute: typeof CreateRoute
  EcoRoute: typeof EcoRoute
  MasterAdminRoute: typeof MasterAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boost': {
      id: '/boost'
      path: '/boost'
      fullPath: '/boost'
      preLoaderRoute: typeof BoostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eco': {
      id: '/eco'
      path: '/eco'
      fullPath: '/eco'
      preLoaderRoute: typeof EcoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-admin': {
      id: '/master-admin'
      path: '/master-admin'
      fullPath: '/master-admin'
      preLoaderRoute: typeof MasterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoostRoute: BoostRoute,
  CreateRoute: CreateRoute,
  EcoRoute: EcoRoute,
  MasterAdminRoute: MasterAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
